name: development-example
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example_build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kosdev-code/kos-buildpublish/kos_builder:dockerimage
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: ${{ github.repository }}
            token: ${{ secrets.GITHUB_TOKEN }}
            path: ${{ github.event.repository.name }}
            lfs: true

      - name: Build and Publish
        env:
            STUDIO_APIKEY: ${{ secrets.STUDIO_APIKEY }}

        working-directory: ./${{ github.event.repository.name }}
        run: |
            kos_build_handler.sh automation .github/development.json
